# Hugo variables
#
baseURL = 'https://gitfaq.org/'
languageCode = 'en-us'
title = 'GitFAQ.org'
theme = "allfaqs"

# number of posts to show on home/category/tag pages (Default: 10)
paginate = 5
# number of words to use for summary on home/category/tag pages (Default: 70)
summaryLength = 50

# optionally override the site's footer with custom copyright text
copyright = "Except where otherwise noted, content on this site is licensed under the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0.html) license."
googleAnalytics = "UA-53866202-1"
#disqusShortname = "XYW"

[permalinks]
posts = "/:year/:month/:title/"
page = "/:slug/"

[[menu.sidebar]]
name = "Made by Candle"
url = "https://candle.dev"


# Theme variables
#
[params]
# Site author
author = "Candle"

# Description/subtitle for homepage (can be Markdown)
description = "Frequently asked questions for git and git workflows."

# Show header (default: true)
header_visible = false

# Format dates with Go's time formatting
date_format = "Mon Jan 02, 2006"

# verification string for Google Webmaster Tools
#google_verify_meta = "BAi57DROASu4b2mkVNA_EyUsobfA7Mq8BmSg7Rn-Zp9"

# verification string for Bing Webmaster Tools
#bing_verify_meta = "3DA353059F945D1AA256B1CD8A3DA847"

# verification string for Yandex Webmaster Tools
#yandex_verify_meta = "66b077430f35f04a"

# Optionally display a message about the site's use of cookies, which may be
# required for your site in the European Union. Set the parameter below to a
# page where the user can get more information about cookies, either on your
# site or externally, for example:
# cookie_consent_info_url = "/cookie-information/"
# cookie_consent_info_url = "http://cookiesandyou.com"

# show sharing icons on pages/posts (default: true)
#sharingicons = true

# Display post summaries instead of content in list templates (default: true)
truncate = false

# Disable the use of sub-resource integrity on CSS/JS assets (default: false)
# Useful if you're using a CDN or other host where you can't control cache headers
#disable_sri = false

[params.sidebar]
# Optional about block for sidebar (can be Markdown)
about = "This FAQ is brought to you by [Candle](https://candle.dev)."

# How many posts to show on the sidebar (Default: 5)
#num_recent_posts = 2

[params.social]
# Optional, used for attribution in Twitter cards (ideally not a person
# for example: nytimes, flickr, NatGeo, etc).
# See: https://dev.twitter.com/cards/types/summary-large-image
twitter = "candle_corp"

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
#DefaultContentLanguage = "en"

# Languages to render
#[languages.en]
#[languages.bg]
# Bulgarian date format is dd.mm.yyyy
#date_format = "02.01.2006"


[markup.highlight]
codeFences = true
style = 'manni'


[module]
# uncomment line below for temporary local development of module
# replacements = "github.com/jsoverson/allfaqs -> ../../allfaqs"
[module.hugoVersion]
extended = true
min = "0.75.0"
[[module.imports]]
path = "github.com/jsoverson/allfaqs"
# path = "file://../bootstrap-list"
disable = false
